### PR TITLE
chore: detect when users unset `tokio_unstable`

### LINKED ISSUE #8126: Error compiling main: `unresolved import tokio::runtime::RuntimeMetrics`
__Steps to reproduce:__
Reproducer:

```shell
cd influxb_iox
cargo test --test  end_to_end -- query_tests
```

This fails with this error:

```
error[E0432]: unresolved import `tokio::runtime::RuntimeMetrics`
  --> tokio_metrics_bridge/src/lib.rs:26:5
   |
26 | use tokio::runtime::RuntimeMetrics;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `RuntimeMetrics` in `runtime`

   Compiling trace_exporters v0.1.0 (/Users/alamb/Software/influxdb_iox2/trace_exporters)
```

__Expected behaviour:__
I expect the code to compile without error

__Environment info:__

Mac x86_64

__Workaound:__

Looking in the docs,  https://docs.rs/tokio/latest/tokio/#unstable-features

I found a workaround which was to set this environment:

```
RUSTFLAGS="--cfg tokio_unstable"
```

However, I would like to be able to build IOx without having to set a RUSTC compiler flag :scream:

This seems to have been introduced in https://github.com/influxdata/influxdb_iox/pull/8091 by @crepererum 

Perhaps we could make the runtime metrics thing an optional feature

### PR DESCRIPTION
**Pull request by crepererum**
Close #8126.

### CODE REVIEW

**Review by domodwyer — APPROVED** [review]

**Comment by domodwyer** [comment]
This is actually pretty annoying - I've already worked around it twice, but it seems to make using directives in `~/.cargo/config.toml` impossible. I have:

```
linker = "clang"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=$LINKER_PATH"]
```

To use a faster linker to speed up builds, but this check fires. Not allowing any rustflags customisation is definitely not ideal!

**Comment by domodwyer** [comment]
I've opened https://github.com/influxdata/influxdb_iox/pull/8136 to change how this works - instead of forcing the cfg to be set (it seems user values take precedence / aren't merged) and blocking builds use the cfg power to make it optional like in tokio.
