### ISSUE TITLE
Error compiling main: `unresolved import tokio::runtime::RuntimeMetrics`

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#8126]
__Steps to reproduce:__
Reproducer:

```shell
cd influxb_iox
cargo test --test  end_to_end -- query_tests
```

This fails with this error:

```
error[E0432]: unresolved import `tokio::runtime::RuntimeMetrics`
  --> tokio_metrics_bridge/src/lib.rs:26:5
   |
26 | use tokio::runtime::RuntimeMetrics;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `RuntimeMetrics` in `runtime`

   Compiling trace_exporters v0.1.0 (/Users/alamb/Software/influxdb_iox2/trace_exporters)
```

__Expected behaviour:__
I expect the code to compile without error

__Environment info:__

Mac x86_64

__Workaound:__

Looking in the docs,  https://docs.rs/tokio/latest/tokio/#unstable-features

I found a workaround which was to set this environment:

```
RUSTFLAGS="--cfg tokio_unstable"
```

However, I would like to be able to build IOx without having to set a RUSTC compiler flag :scream:

This seems to have been introduced in https://github.com/influxdata/influxdb_iox/pull/8091 by @crepererum 

Perhaps we could make the runtime metrics thing an optional feature

**Comment by appletreeisyellow** [comment]
I just pulled the `influxdb_iox` repo and I'm able to compile and run `cargo test --test  end_to_end -- query_tests` successfully

**Comment by alamb** [comment]
🤔  I wonder if it could be related to the fact I have  `RUSTFLAGS` set in my environment already

```
$ echo $RUSTFLAGS
-C debuginfo=1
```

**Comment by appletreeisyellow** [comment]
Probably 🤔 I got nothing when I do `echo $RUSTFLAGS`

**Comment by alamb** [comment]
I wonder if this is the same root cause of the build problem / outage last week -- about RUSTFLAGS not stacking: https://github.com/influxdata/idpe/issues/17801

**Comment by crepererum** [comment]
Yes. Don't set `RUSTFLAGS`. If you think that you need additional flags for your platform or another profile, please adjust https://github.com/influxdata/influxdb_iox/blob/main/.cargo/config or https://github.com/influxdata/influxdb_iox/blob/main/Cargo.toml .

**Comment by crepererum** [comment]
I've added a detection+advice system in #8133.

**Comment by alamb** [comment]
> please adjust https://github.com/influxdata/influxdb_iox/blob/main/.cargo/config or https://github.com/influxdata/influxdb_iox/blob/main/Cargo.toml .

I will figure out how to make this work for my needs. The problem with changing those settings is I think they affect all users (not just me). 

The particular thing I was doing (turning off debug symbols to speed up my compilation time) was not universally liked (e.g. @tustvold uses the debugger and thus debug symbols are important to him)

**Comment by crepererum** [comment]
You could have a `quick-debug` profile if you wan.
